name: Verify Hosts Validity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run docker-compose
      run: docker compose up -d

    - name: Test frontend
      run: |
        if ! curl -I http://localhost:8080; then
          echo "Frontend non risponde"
          exit 1
        fi

    - name: Test WS service port
      run: |
        if ! nc -z localhost 3333; then
          echo "WebSocket service not responding on port 3333"
          exit 1
        fi

    - name: Stop containers
      if: always()
      run: docker compose down
